server:
  port: 7001

spring.data.mongodb:
  uri: http://ip172-18-0-28-bq61fitim9m000b89m40-27017.direct.labs.play-with-docker.com/
  #host: localhost
  #port: 27017
  database: product-db

spring.cloud.stream:
  defaultBinder: rabbit
  default.contentType: application/json
  bindings.input:
    destination: products
    group: productsGroup
    consumer:
      maxAttempts: 3
      backOffInitialInterval: 500
      backOffMaxInterval: 1000
      backOffMultiplier: 2.0

  rabbit.bindings.input.consumer:
    autoBindDlq: true
    republishToDlq: true

  kafka.bindings.input.consumer:
    enableDlq: true

logging:
  level:
    root: INFO
    com.habeebcycle: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG

---
spring:
  profiles: docker
  data:
    mongodb:
      host: mongodb

server:
  port: 8080

---
spring:
  profiles: streaming_partitioned
  cloud.stream.bindings.input.consumer:
    partitioned: true
    instanceCount: 2

---
spring:
  profiles: streaming_instance_0
  cloud.stream.bindings.input.consumer.instanceIndex: 0

---
spring:
  profiles: streaming_instance_1
  cloud.stream.bindings.input.consumer.instanceIndex: 1

---
spring:
  profiles: kafka
  cloud.stream.defaultBinder: kafka

management.health.rabbit.enabled: false
